services:
  neto_openmetrics.collector:
    public: true
    class: Neto\OpenmetricsBundle\Metrics\PrometheusCollector
    arguments:
      - "%neto_openmetrics.namespace%"
      - "@Prometheus\\CollectorRegistry"

  neto_openmetrics.adaptor:
    class: Prometheus\Storage\APC

  Prometheus\CollectorRegistry:
    class: Prometheus\CollectorRegistry
    arguments:
      - "@neto_openmetrics.adaptor"

  Neto\OpenmetricsBundle\Controller\MetricsController:
    public: true
    class: Neto\OpenmetricsBundle\Controller\MetricsController
    arguments:
      - "@Prometheus\\CollectorRegistry"

  Neto\OpenmetricsBundle\Event\KernelEventListener:
    class: Neto\OpenmetricsBundle\Event\KernelEventListener
    arguments:
      - "@neto_openmetrics.collector"
      - "%neto_openmetrics.ignored_routes%"
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  Neto\OpenmetricsBundle\DBAL\Logging\DoctrineQueryMetricsLogger:
    class: Neto\OpenmetricsBundle\DBAL\Logging\DoctrineQueryMetricsLogger
    arguments:
      - "@neto_openmetrics.collector"
